# fish completion for furl / furls
# Install: copy to ~/.config/fish/completions/

for cmd in furl furls
    complete -c $cmd -s j -l json -d 'Serialize data items as JSON (default)'
    complete -c $cmd -s f -l form -d 'Serialize data items as form fields'
    complete -c $cmd -l multipart -d 'Send a multipart/form-data request'
    complete -c $cmd -l boundary -x -d 'Custom multipart boundary'
    complete -c $cmd -l raw -x -d 'Pass raw request data'
    complete -c $cmd -s x -l compress -d 'Compress the request body with Deflate'
    complete -c $cmd -l pretty -x -a 'all colors format none' -d 'Output processing'
    complete -c $cmd -s s -l style -x -d 'Output color scheme'
    complete -c $cmd -l unsorted -d 'Disable output sorting'
    complete -c $cmd -l sorted -d 'Enable output sorting'
    complete -c $cmd -l response-charset -x -d 'Override response encoding'
    complete -c $cmd -l response-mime -x -d 'Override response MIME type'
    complete -c $cmd -l format-options -x -d 'Tune output formatting'
    complete -c $cmd -s p -l print -x -d 'Parts of the exchange to print'
    complete -c $cmd -s h -l headers -d 'Print only response headers'
    complete -c $cmd -s m -l meta -d 'Print only response metadata'
    complete -c $cmd -s b -l body -d 'Print only the response body'
    complete -c $cmd -s v -l verbose -d 'Print the whole exchange'
    complete -c $cmd -l all -d 'Show intermediary exchanges too'
    complete -c $cmd -s S -l stream -d 'Stream the response body'
    complete -c $cmd -s o -l output -r -d 'Write output to FILE'
    complete -c $cmd -s d -l download -d 'Save the response body to a file'
    complete -c $cmd -s c -l continue -d 'Resume an interrupted download'
    complete -c $cmd -s q -l quiet -d 'Silence terminal output'
    complete -c $cmd -l session -x -d 'Reuse and update a named session'
    complete -c $cmd -l session-read-only -x -d 'Use a session read-only'
    complete -c $cmd -s a -l auth -x -d 'Credentials USER[:PASS]'
    complete -c $cmd -s A -l auth-type -x -a 'basic bearer digest' -d 'Auth mechanism'
    complete -c $cmd -l ignore-netrc -d 'Never read .netrc'
    complete -c $cmd -l offline -d 'Build and print the request without sending'
    complete -c $cmd -l proxy -x -d 'PROTOCOL:PROXY_URL'
    complete -c $cmd -s F -l follow -d 'Follow 30x redirects'
    complete -c $cmd -l max-redirects -x -d 'Redirect limit'
    complete -c $cmd -l max-headers -x -d 'Max response header count'
    complete -c $cmd -l timeout -x -d 'Socket idle timeout in seconds'
    complete -c $cmd -l check-status -d 'Reflect HTTP status in the exit code'
    complete -c $cmd -l path-as-is -d 'Keep dot segments in the URL path'
    complete -c $cmd -l chunked -d 'Chunked transfer encoding'
    complete -c $cmd -l verify -x -d 'TLS verification: yes/no/CA path'
    complete -c $cmd -l ssl -x -a 'tls1.2 tls1.3' -d 'Force a TLS version'
    complete -c $cmd -l ciphers -x -d 'Allowed TLS cipher suites'
    complete -c $cmd -l cert -r -d 'Client certificate (PEM)'
    complete -c $cmd -l cert-key -r -d 'Client private key'
    complete -c $cmd -l cert-key-pass -x -d 'Passphrase for the key'
    complete -c $cmd -s I -l ignore-stdin -d 'Never read piped stdin'
    complete -c $cmd -l help -d 'Show help'
    complete -c $cmd -l manual -d 'Show the manual'
    complete -c $cmd -l version -d 'Show the version'
    complete -c $cmd -l traceback -d 'Print the full error backtrace'
    complete -c $cmd -l default-scheme -x -d 'Scheme for scheme-less URLs'
    complete -c $cmd -l debug -d 'Print diagnostic information'
end
